### ISSUE TITLE
Error when creating a job

### ISSUE THREAD

**Issue by franvarney** [franvarney/franvarney-api#1]
Mongoose v 4.3.4
Does not happen in 4.1.12

```
Debug: internal, implementation, error 
    TypeError: Uncaught error: cb is not a function
    at /Users/fran/Documents/Development/Sandbox/Node/franvarney-api/node_modules/mongoose-shortid-nodeps/lib/index.js:31:17
    at /Users/fran/Documents/Development/Sandbox/Node/franvarney-api/node_modules/mongoose/lib/model.js:295:13
    at /Users/fran/Documents/Development/Sandbox/Node/franvarney-api/node_modules/mongoose/lib/model.js:230:5
    at /Users/fran/Documents/Development/Sandbox/Node/franvarney-api/node_modules/mongoose/lib/model.js:139:7
    at /Users/fran/Documents/Development/Sandbox/Node/franvarney-api/node_modules/mongodb/lib/collection.js:485:5
    at /Users/fran/Documents/Development/Sandbox/Node/franvarney-api/node_modules/mongodb/lib/collection.js:643:5
    at /Users/fran/Documents/Development/Sandbox/Node/franvarney-api/node_modules/mongodb/lib/bulk/unordered.js:469:9
    at resultHandler (/Users/fran/Documents/Development/Sandbox/Node/franvarney-api/node_modules/mongodb/lib/bulk/unordered.js:416:5)
    at /Users/fran/Documents/Development/Sandbox/Node/franvarney-api/node_modules/mongodb-core/lib/topologies/server.js:780:13
    at bound (domain.js:250:14)
    at runBound (domain.js:263:12)
    at [object Object].Callbacks.emit (/Users/fran/Documents/Development/Sandbox/Node/franvarney-api/node_modules/mongodb-core/lib/topologies/server.js:95:3)
    at [object Object].messageHandler (/Users/fran/Documents/Development/Sandbox/Node/franvarney-api/node_modules/mongodb-core/lib/topologies/server.js:249:23)
    at Socket.<anonymous> (/Users/fran/Documents/Development/Sandbox/Node/franvarney-api/node_modules/mongodb-core/lib/connection/connection.js:265:22)
    at emitOne (events.js:77:13)
    at Socket.emit (events.js:169:7)
```

without ShortId in models/job

```
Debug: internal, implementation, error 
    TypeError: Uncaught error: callback is not a function
    at /Users/fran/Documents/Development/Sandbox/Node/franvarney-api/node_modules/mongoose/lib/model.js:230:5
    at /Users/fran/Documents/Development/Sandbox/Node/franvarney-api/node_modules/mongoose/lib/model.js:139:7
    at /Users/fran/Documents/Development/Sandbox/Node/franvarney-api/node_modules/mongodb/lib/collection.js:485:5
    at /Users/fran/Documents/Development/Sandbox/Node/franvarney-api/node_modules/mongodb/lib/collection.js:643:5
    at /Users/fran/Documents/Development/Sandbox/Node/franvarney-api/node_modules/mongodb/lib/bulk/unordered.js:469:9
    at resultHandler (/Users/fran/Documents/Development/Sandbox/Node/franvarney-api/node_modules/mongodb/lib/bulk/unordered.js:416:5)
    at /Users/fran/Documents/Development/Sandbox/Node/franvarney-api/node_modules/mongodb-core/lib/topologies/server.js:780:13
    at bound (domain.js:250:14)
    at runBound (domain.js:263:12)
    at [object Object].Callbacks.emit (/Users/fran/Documents/Development/Sandbox/Node/franvarney-api/node_modules/mongodb-core/lib/topologies/server.js:95:3)
    at [object Object].messageHandler (/Users/fran/Documents/Development/Sandbox/Node/franvarney-api/node_modules/mongodb-core/lib/topologies/server.js:249:23)
    at Socket.<anonymous> (/Users/fran/Documents/Development/Sandbox/Node/franvarney-api/node_modules/mongodb-core/lib/connection/connection.js:265:22)
    at emitOne (events.js:77:13)
    at Socket.emit (events.js:169:7)
    at readableAddChunk (_stream_readable.js:146:16)
    at Socket.Readable.push (_stream_readable.js:110:10)
```

**Comment by franvarney** [comment]
This is something with Mongoose or maybe Babel
